#!/usr/bin/env python3
"""Lift traced ARM/Thumb instructions once and emit a native C routine."""
import argparse
import json
import os
import re
import sys

import pypcode

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'synthDrivers'))
from _nokia.harness.romrun import load_rom


def cname(v):
    if v.space.name in ('const', 'ram'):
        return f'UINT64_C({v.offset})'
    if v.space.name == 'register':
        return 'reg_' + re.sub(r'[^A-Za-z0-9_]', '_', str(v))
    if v.space.name == 'unique':
        return f'u_{v.offset:x}'
    raise ValueError(f'unsupported space {v.space.name}: {v}')


def mask(size):
    return 'UINT64_MAX' if size >= 8 else f'UINT64_C(0x{(1 << (8 * size)) - 1:x})'


def value(v):
    if v.space.name == 'ram':
        return f'(nokia_mem_load(&machine, UINT64_C({v.offset}), {v.size}) & {mask(v.size)})'
    return f'({cname(v)} & {mask(v.size)})'


def signed(v):
    return f'nokia_sext({value(v)}, {v.size})'


def assign(out, expression):
    return f'{cname(out)} = ((uint64_t)({expression})) & {mask(out.size)};'


def target(v):
    if v.space.name != 'ram':
        raise ValueError(f'non-RAM control target: {v}')
    return v.offset & ~1


def emit_op(op, known, address, size, thumb):
    name, out, ins = op.opcode.name, op.output, list(op.inputs)
    if name == 'IMARK':
        return []
    if name == 'COPY':
        return [assign(out, value(ins[0]))]
    binary = {'INT_ADD': '+', 'INT_SUB': '-', 'INT_MULT': '*',
              'INT_AND': '&', 'INT_OR': '|', 'INT_XOR': '^',
              'BOOL_AND': '&&', 'BOOL_OR': '||', 'BOOL_XOR': '!='}
    if name in binary:
        return [assign(out, f'{value(ins[0])} {binary[name]} {value(ins[1])}')]
    if name == 'INT_LEFT':
        return [assign(out, f'nokia_shl({value(ins[0])}, {value(ins[1])}, {ins[0].size})')]
    if name == 'INT_RIGHT':
        return [assign(out, f'nokia_shr({value(ins[0])}, {value(ins[1])}, {ins[0].size})')]
    if name == 'INT_SRIGHT':
        return [assign(out, f'nokia_sar({value(ins[0])}, {value(ins[1])}, {ins[0].size})')]
    if name == 'INT_EQUAL':
        return [assign(out, f'{value(ins[0])} == {value(ins[1])}')]
    if name == 'INT_NOTEQUAL':
        return [assign(out, f'{value(ins[0])} != {value(ins[1])}')]
    if name == 'INT_SLESS':
        return [assign(out, f'{signed(ins[0])} < {signed(ins[1])}')]
    if name == 'INT_LESSEQUAL':
        return [assign(out, f'{value(ins[0])} <= {value(ins[1])}')]
    if name == 'BOOL_NEGATE':
        return [assign(out, f'!{value(ins[0])}')]
    if name == 'INT_NEGATE':
        return [assign(out, f'~{value(ins[0])}')]
    if name == 'INT_ZEXT':
        return [assign(out, value(ins[0]))]
    if name == 'INT_SEXT':
        return [assign(out, f'nokia_sext({value(ins[0])}, {ins[0].size})')]
    if name == 'SUBPIECE':
        return [assign(out, f'{value(ins[0])} >> (8 * {value(ins[1])})')]
    if name == 'INT_CARRY':
        return [assign(out, f'nokia_carry({value(ins[0])}, {value(ins[1])}, {ins[0].size})')]
    if name == 'INT_SCARRY':
        return [assign(out, f'nokia_scarry({value(ins[0])}, {value(ins[1])}, {ins[0].size})')]
    if name == 'INT_SBORROW':
        return [assign(out, f'nokia_sborrow({value(ins[0])}, {value(ins[1])}, {ins[0].size})')]
    if name == 'LOAD':
        return [assign(out, f'nokia_mem_load(&machine, {value(ins[1])}, {out.size})')]
    if name == 'STORE':
        return [f'if (!nokia_mem_store(&machine, {value(ins[1])}, {value(ins[2])}, {ins[2].size})) goto unsupported;']
    if name == 'CALLOTHER':
        return []  # setISAMode; dispatch already masks the Thumb bit
    if name == 'CBRANCH':
        dest = target(ins[0])
        return [f'if ({value(ins[1])}) goto {f"L_{dest:08x}" if dest in known else "unsupported"};']
    if name in ('BRANCH', 'CALL'):
        dest = target(ins[0])
        statements = []
        if name == 'CALL':
            statements.append(
                f'reg_lr = UINT64_C({(address + size) | (1 if thumb else 0)});')
        statements.append(
            f'goto {f"L_{dest:08x}" if dest in known else "unsupported"};')
        return statements
    if name in ('BRANCHIND', 'RETURN'):
        return [f'reg_pc = {value(ins[0])};', 'goto dispatch;']
    raise ValueError(f'unsupported P-code operation: {op}')


HEADER = r'''/* Generated by tools/generate_klatt_aot.py. */
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#ifdef _WIN32
#define NOKIA_EXPORT __declspec(dllexport)
#else
#define NOKIA_EXPORT __attribute__((visibility("default")))
#endif
typedef struct { uint8_t data[0x10000]; const uint8_t *rom; uint32_t rom_base; size_t rom_size; uint32_t bad_address; } NokiaAotMachine;
static uint64_t nokia_mask(unsigned s) { return s >= 8 ? UINT64_MAX : (UINT64_C(1) << (s * 8)) - 1; }
static int64_t nokia_sext(uint64_t v, unsigned s) { unsigned b=s*8; uint64_t m=UINT64_C(1)<<(b-1); v&=nokia_mask(s); return (int64_t)((v^m)-m); }
static uint64_t nokia_shl(uint64_t v,uint64_t n,unsigned s) { return n>=s*8?0:(v<<n)&nokia_mask(s); }
static uint64_t nokia_shr(uint64_t v,uint64_t n,unsigned s) { return n>=s*8?0:(v&nokia_mask(s))>>n; }
static uint64_t nokia_sar(uint64_t v,uint64_t n,unsigned s) { unsigned b=s*8; if(n>=b)return nokia_sext(v,s)<0?nokia_mask(s):0; return ((uint64_t)(nokia_sext(v,s)>>n))&nokia_mask(s); }
static uint64_t nokia_carry(uint64_t a,uint64_t b,unsigned s) { uint64_t m=nokia_mask(s); return (a&m)>m-(b&m); }
static uint64_t nokia_scarry(uint64_t a,uint64_t b,unsigned s) { int64_t x=nokia_sext(a,s),y=nokia_sext(b,s),r=nokia_sext((a+b)&nokia_mask(s),s); return (x>=0&&y>=0&&r<0)||(x<0&&y<0&&r>=0); }
static uint64_t nokia_sborrow(uint64_t a,uint64_t b,unsigned s) { int64_t x=nokia_sext(a,s),y=nokia_sext(b,s),r=nokia_sext((a-b)&nokia_mask(s),s); return (x>=0&&y<0&&r<0)||(x<0&&y>=0&&r>=0); }
static uint64_t nokia_mem_load(NokiaAotMachine*m,uint64_t address,unsigned size) { uint64_t v=0; uint32_t a=(uint32_t)address; if((uint64_t)a+size<=sizeof(m->data))memcpy(&v,m->data+a,size); else if(a>=m->rom_base&&(uint64_t)(a-m->rom_base)+size<=m->rom_size)memcpy(&v,m->rom+(a-m->rom_base),size); else { if(!m->bad_address)m->bad_address=a; return UINT64_MAX; } return v; }
static int nokia_mem_store(NokiaAotMachine*m,uint64_t address,uint64_t value,unsigned size) { uint32_t a=(uint32_t)address; if((uint64_t)a+size>sizeof(m->data))return 0; memcpy(m->data+a,&value,size); return 1; }
static uint32_t nokia_last_pc, nokia_last_r0, nokia_last_r7, nokia_last_bad_address;
static uint32_t nokia_snapshot[8];
static uint32_t nokia_div_count, nokia_div_trace[192];
NOKIA_EXPORT uint32_t nokia_klatt_last_pc(void) { return nokia_last_pc; }
NOKIA_EXPORT uint32_t nokia_klatt_last_r0(void) { return nokia_last_r0; }
NOKIA_EXPORT uint32_t nokia_klatt_last_r7(void) { return nokia_last_r7; }
NOKIA_EXPORT uint32_t nokia_klatt_last_bad_address(void) { return nokia_last_bad_address; }
NOKIA_EXPORT uint32_t nokia_klatt_div_count(void) { return nokia_div_count; }
NOKIA_EXPORT uint32_t nokia_klatt_div_trace(uint32_t n) { return n<192?nokia_div_trace[n]:0; }
NOKIA_EXPORT uint32_t nokia_klatt_snapshot(uint32_t n) { return n<8?nokia_snapshot[n]:0; }
NOKIA_EXPORT int nokia_klatt_generate_aot(int16_t*output,int32_t*peak,uint8_t parameters[122],uint8_t state[564],uint32_t gain,const uint8_t*rom,uint32_t rom_base,size_t rom_size,uint32_t caller_after[5]) {
    NokiaAotMachine machine;
'''


def generate(rom_path, trace_path, output_path):
    trace = json.load(open(trace_path, encoding='utf-8'))
    blob = load_rom(rom_path)
    base = blob.packed_base
    seen = {item['address'] for item in trace['instructions']}
    # Unicorn starts its code hook eight bytes into Symbian's signed-division
    # helper after an interworking veneer. Recognise the helper by its stable
    # ARM prologue instead of hard-coding one phone's ROM address.
    idiv_targets, udivmod_targets = set(), set()
    for item in trace['instructions']:
        address = item['address']
        raw = bytes(blob[address-base:address-base+8])
        if raw[:4] == bytes.fromhex('04f01fe5') and len(raw) == 8:
            candidate = int.from_bytes(raw[4:8], 'little') & ~1
            prologue = bytes(blob[candidate-base:candidate-base+8])
            if prologue == bytes.fromhex('01c090e12100004a'):
                idiv_targets.add(candidate)
            elif prologue == bytes.fromhex('20c271e00020a0e3'):
                udivmod_targets.add(candidate)
    contexts = {True: pypcode.Context('ARM:LE:32:v8T'), False: pypcode.Context('ARM:LE:32:v8')}
    lifted, registers, uniques = {}, {}, {}
    for item in trace['instructions']:
        address = item['address']
        trans = contexts[item['thumb']].translate(bytes(blob[address-base:address-base+8]), base_address=address, max_instructions=1)
        lifted[address] = (item['size'], list(trans.ops))
        for op in trans.ops:
            for node in ([op.output] if op.output is not None else []) + list(op.inputs):
                if node.space.name == 'register': registers[cname(node)] = max(registers.get(cname(node), 0), node.size)
                elif node.space.name == 'unique': uniques[cname(node)] = max(uniques.get(cname(node), 0), node.size)
    known = set(lifted)
    lines = [HEADER]
    lines += [f'    uint64_t {name}=0;' for name in sorted(registers)]
    lines += [f'    uint64_t {name}=0;' for name in sorted(uniques)]
    lines += ['    uint32_t nokia_at=0; nokia_div_count=0; memset(&machine,0,sizeof(machine));',
              '    machine.rom=rom; machine.rom_base=rom_base; machine.rom_size=rom_size;',
              '    memcpy(machine.data+0x6000,parameters,122); memcpy(machine.data+0x7000,state,564);',
              '    memcpy(machine.data+0x5000,peak,4); memcpy(machine.data+0xf000,&gain,4);',
              '    reg_r0=0x1000; reg_r1=0x5000; reg_r2=0x6000; reg_r3=0x7000; reg_sp=0xf000; reg_lr=0xdead0001; reg_pc=0;',
              f'    goto L_{trace["entry"]:08x};', 'dispatch:', '    switch((uint32_t)reg_pc&~1u){',
              '    case 0xdead0000u: goto finished;']
    lines += [f'    case 0x{a:08x}u: goto helper_idiv;' for a in sorted(idiv_targets)]
    lines += [f'    case 0x{a:08x}u: goto helper_udivmod;' for a in sorted(udivmod_targets)]
    lines += [f'    case 0x{a:08x}u: goto L_{a:08x};' for a in sorted(known)
              if a not in idiv_targets and a not in udivmod_targets]
    lines += ['    default: goto unsupported;', '    }']
    for address in sorted(lifted):
        size, ops = lifted[address]
        lines.append(f'L_{address:08x}:')
        lines.append(f'    nokia_at=0x{address:08x}u;')
        if address == 0x830f9e56:
            lines.append('    nokia_snapshot[0]=reg_r0; nokia_snapshot[1]=reg_r1; nokia_snapshot[2]=reg_r2; nokia_snapshot[3]=reg_r3; nokia_snapshot[4]=reg_r4; nokia_snapshot[5]=reg_r5; nokia_snapshot[6]=reg_r6; nokia_snapshot[7]=reg_r7;')
        controlled = False
        for op in ops:
            lines += ['    ' + statement for statement in
                      emit_op(op, known, address, size,
                              next(item['thumb'] for item in trace['instructions']
                                   if item['address'] == address))]
            controlled |= op.opcode.name in ('BRANCH', 'CALL', 'BRANCHIND', 'RETURN')
        if not controlled:
            nxt = address + size
            lines.append(f'    goto L_{nxt:08x};' if nxt in known else '    goto unsupported;')
    lines += ['helper_idiv:',
              '    { int32_t a=(int32_t)reg_r0,b=(int32_t)reg_r1; if(!b)goto unsupported; if(nokia_div_count<64){uint32_t n=nokia_div_count*3;nokia_div_trace[n]=(uint32_t)a;nokia_div_trace[n+1]=(uint32_t)b;nokia_div_trace[n+2]=(uint32_t)(a/b);} nokia_div_count++; reg_r0=(uint32_t)(a/b); reg_pc=reg_lr; goto dispatch; }',
              'helper_udivmod:',
              '    { uint32_t a=(uint32_t)reg_r0,b=(uint32_t)reg_r1; if(!b)goto unsupported; reg_r0=a/b; reg_r1=a%b; reg_pc=reg_lr; goto dispatch; }',
              'finished:', '    { int16_t n; memcpy(&n,machine.data+0x6002,2); if(n<0||n>8192)goto unsupported; memcpy(output,machine.data+0x1000,(size_t)n*2); }',
              '    memcpy(peak,machine.data+0x5000,4); memcpy(parameters,machine.data+0x6000,122); memcpy(state,machine.data+0x7000,564);',
              '    if(caller_after){ caller_after[0]=(uint32_t)reg_r1; caller_after[1]=(uint32_t)reg_r2; caller_after[2]=(uint32_t)reg_r3; caller_after[3]=(uint32_t)reg_r12; caller_after[4]=((uint32_t)(reg_NG&1)<<31)|((uint32_t)(reg_ZR&1)<<30)|((uint32_t)(reg_CY&1)<<29)|((uint32_t)(reg_OV&1)<<28); } return 1;',
              'unsupported:', '    nokia_last_pc=nokia_at; nokia_last_r0=(uint32_t)reg_r0; nokia_last_r7=(uint32_t)reg_r7; nokia_last_bad_address=machine.bad_address; return 0;', '}', '']
    with open(output_path, 'w', encoding='utf-8', newline='\n') as stream:
        stream.write('\n'.join(lines))
    print(f'{len(lifted)} instructions -> {output_path}')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--rom', required=True); parser.add_argument('--trace', required=True); parser.add_argument('--output', required=True)
    args = parser.parse_args(); generate(args.rom, args.trace, args.output)


if __name__ == '__main__':
    main()
